apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: mensagem-boas-vindas
spec:
  steps:
    - name: exibir-mensagem
      image: alpine:3.20
      script: |
        #!/bin/sh
        echo "Bem vindo ao tekton"

---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: pipeline-boas-vindas
spec:
  tasks:
    - name: boas-vindas
      taskRef:
        name: mensagem-boas-vindas

---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: template-boas-vindas
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: pipeline-boas-vindas-run-
      spec:
        pipelineRef:
          name: pipeline-boas-vindas

---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: listener-boas-vindas
spec:
  triggers:
    - name: trigger-boas-vindas
      template:
        ref: template-boas-vindas